### ISSUE TITLE
WithApollo opts-out of Automatic Static Optimization due to `getInitialProps`

### ISSUE THREAD

**Issue by hugomn** [borisowsky/next-advanced-apollo-starter#16]
Hello @borisowsky! Thanks a lot for this starter. This is the best apollo + next + typescript + ssr setup I've seen so far.

But I'm getting this warning:
```
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
Read more: https://err.sh/next.js/opt-out-auto-static-optimization
```

It's due to this line: https://github.com/borisowsky/next-advanced-starter/blob/7c893b932973dcbfebcdf861e21e1606b6105131/src/lib/apollo/apollo.tsx#L120 that will add `getInitialProps` to the `Component <App>`. 

This causes all non-getStaticProps pages to be executed on the server -- disabling Automatic Static Optimization.

I tried to come up with a solution but couldn't find a way to correctly call `getDataFromTree`. Is there any solution for that?

**Comment by borisowsky** [comment]
@hugomn `withApollo({ ssr: false })(Component)` - you're talking about this?

**Comment by hugomn** [comment]
Exactly, because you are adding the `withApollo`  hook in the custom app, which means that all static pages will be executed on the server side.

**Comment by borisowsky** [comment]
@hugomn you can remove withApollo from _app.tsx and use it on individual pages.

**Comment by msreekm** [comment]
thanks for the starter project- 2 questions about dataFromTree ,where is AppTree being enabled or disabled?
   // Only if dataFromTree is enabled
        if (ssr && AppTree) {
        }

Also  about this comment, how does fragment solve the multiple rendering on server?
           //This method can be pretty slow since it renders
            // your entire AppTree once for every query. Check out apollo fragments
            // if you want to reduce the number of rerenders.

**Comment by borisowsky** [comment]
Due to latest updates this is not a issue anymore.
