### ISSUE TITLE
How should I use Apollo client in GetStaticProps?

### ISSUE THREAD

**Issue by idreamer** [borisowsky/next-advanced-apollo-starter#20]
Thanks for sharing your codes. 

By the way, I would like to use SSG instead of SSR. 
Could you show an example to use `getStaticProps` with your structure?

**Comment by borisowsky** [comment]
@idreamer Sorry for huge delay, I have not so much power to support this repository.
I just updated Apollo Client setup to latest version, so you can use `getStaticProps` as in base `with-apollo` example: https://github.com/vercel/next.js/blob/canary/examples/with-apollo/pages/index.js#L20-L32

But also, you can use it with `getServerSideProps` like so:
```js
export async function getServerSideProps(ctx) {
  // You need to pass ctx here, so it can get authorization token from request on SSR to pass it in headers
  const apolloClient = initializeApollo(null, ctx);

  await apolloClient.query({
    query: ALL_POSTS_QUERY,
  });

  return addApolloState(apolloClient, {
    props: {},
  });
}
```

**Comment by dominik-myszkowski** [comment]
The return statement for getStaticProps does not accept "addApolloState" return val. Should I use just flat object: { props: {} } ?
